=== qt/qtbase/tests/auto/corelib/xml/qxmlstream/XML-Test-Suite/xmlconf/testcases.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    @(#)testcases.dtd	1.6 99/01/21
    Original version copyright 1998 by Sun Microsystems, Inc.
    All Rights Reserved.
    Modifications copyright 1999 by OASIS.

    1999-06-09 00:20

    DTD describing a database of XML tests.

    NOTE:  the OASIS/NIST test effort also has a DTD for its test
    environment, but that DTD is not yet suited for automated test
    processing.  (Among other issues, it doesn't record information
    putting any test case into the test matrix.)  If that gets fixed,
    it may be useful to switch over to that DTD.
-->

<!--
    The root element of the whole collection is TESTSUITE.  While not
    very different from TESTCASES, it must be distinguished due to
    improper processing by IE5.
-->
<!ELEMENT TESTSUITE ( TESTCASES+ )>
<!ATTLIST TESTSUITE 
    PROFILE	CDATA		#IMPLIED
    >

<!--
    The root element of a collection should be "TESTCASES".  It groups 
    a set of tests in a particular "PROFILE", which is descriptive.  For
    example, a "Japanese" profile might group tests with documents
    in standard Japanese encodings, using Japanese characters used
    inside names and name tokens as well as inside text.  Or the
    profile might be associated with the test supplier.
-->

<!ELEMENT TESTCASES (TEST|TESTCASES)*>
<!ATTLIST TESTCASES
    xml:base	CDATA		#IMPLIED
    PROFILE	CDATA		#IMPLIED
    >

<!--
    The body of each TEST element is its description, used
    to evaluate the diagnostic produced on negative tests.
    People will generally read this to evaluate whether the
    test failed for the correct reason.

    The type of (external) ENTITIES required affect the results
    permitted for certain types of nonvalidating parsers.  In
    some cases, errors (even well-formedness errors) can't be seen
    without reading external parameter or general entities.

    Each test has a unique ID used in diagnostics.

    Tests with an OUTPUT attribute do dual duty:  not only must parsers
    accept the test, but the data they report must also have "Second
    Canonical Form" as found in the specified output file.  (This is
    what James Clark titled "Canonical XML", with the addition of the
    NOTATION declarations that all XML parsers are required to report.)

    The OUTPUT3 attribute is like OUTPUT, but when sent through a
    validating parser the data reported must have the "Third Canonical
    Form" as found in the specified output file.  (This is Second
    Canonical form, with declarations of unparsed ENTITY values and
    with all ignorable whitespace removed.)

    The canonical forms are changed slightly for output files corresponding
    to XML 1.1 input files.  They start with an XML declaration specifying the
    version number, and use character references for all C0 and C1 controls.
    The grammars are changed as follows:


    CanonXML    ::= '<?xml version="1.1">' Pi* element Pi*
    CanonXML2   ::= '<?xml version="1.1">' DTD2? Pi* element Pi*
    CanonXML3   ::= '<?xml version="1.1">' DTD3? Pi* element Pi*
    C0          ::= (Unicode characters #x1-#x1F)
    C1          ::= (Unicode characters #x7F-#x9F)
    EscapedC0   ::= (Decimal references to C0 characters, &#1; - &#31;)
    EscapedC1   ::= (Decimal references to C1 characters, &#127; - &#159;)
    Datachar    ::= '&amp;' | '&lt;' | '&gt;' | '&quot;'
                  | EscapedC0 | EscapedC1
                  | (Char - ('&' | '<' | '>' | '"' | C0 | C1))


    where Char is the XML 1.1 rather than 1.0 production of that name.
 

    Tests apply to one or more particular SECTIONS.

    Each test has a TYPE:
    * All parsers must accept "valid" testcases.
    * Nonvalidating parsers must also accept "invalid" testcases,
      but validating ones must reject them.
    * No parser should accept a "not-wf" testcase unless it's a
      nonvalidating parser and the test contains external entities
      that the parser doesn't read.
    * Parsers are not required to report "errors".

    Each test is in a particular XML document, with a URI.  If these
    tests are accessed over a network, the path will be relative to
    the base URI of the document holding the testcase.

    Tests which apply only to certain versions of XML list those versions
    in the VERSION attribute.  An absent VERSION implies that the test
    applies to all versions.  Parsers should not run tests for versions
    they do not support.

    Parsers should enable namespace processing except for tests marked
    with NAMESPACES="no".  These are tests that use colons in ways
    inconsistent with the Namespaces spec.
-->

<!ELEMENT TEST (#PCDATA | EM | B)*>


<!ATTLIST TEST
    ENTITIES    	(both|none|parameter|general)   "none"
    ID          	ID                              #REQUIRED
    OUTPUT		CDATA				#IMPLIED
    OUTPUT3		CDATA				#IMPLIED
    SECTIONS    	CDATA                           #REQUIRED
    RECOMMENDATION 	(XML1.0|XML1.1|NS1.0|NS1.1|
    			 XML1.0-errata2e|XML1.0-errata3e|
			 NS1.0-errata1e) 	"XML1.0"
    TYPE        	(valid|invalid|not-wf|error)    #REQUIRED
    VERSION 	        NMTOKENS 			#IMPLIED
    URI         	CDATA                           #REQUIRED
    NAMESPACE   	(yes|no)			"yes"
    >

<!--
    Really basic HTML font tweaks, to support highlighting
    some aspects of test descriptions ...
    EM == emphasis (e.g. italics, fun colors)
    B == bold
-->
<!ELEMENT EM (#PCDATA | B)*>
<!ELEMENT B (#PCDATA | EM)*>

=== qt/qtbase/tests/auto/corelib/serialization/qxmlstream/XML-Test-Suite/xmlconf/xmlconf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    @(#)conformance.xml	1.1 98/12/20
    Original version copyright 1998 by Sun Microsystems, Inc.
    All Rights Reserved.
    Modifications copyright 1999 by OASIS.
    Modifications copyright 2001 by OASIS.
-->
<?xml-stylesheet href="xmlconformance.xsl" type="text/xsl"?>
<!DOCTYPE TESTSUITE SYSTEM "testcases.dtd" [

    <!-- Sun-written testcases -->
    <!ENTITY sun-valid		SYSTEM "sun/sun-valid.xml">
    <!ENTITY sun-invalid	SYSTEM "sun/sun-invalid.xml">
    <!ENTITY sun-not-wf		SYSTEM "sun/sun-not-wf.xml">
    <!ENTITY sun-error		SYSTEM "sun/sun-error.xml">

    <!-- James Clark "XMLTEST" -->
    <!ENTITY jclark-xmltest	SYSTEM "xmltest/xmltest.xml">

    <!-- Fuji Xerox "Japanese Documents" -->
    <!ENTITY xerox-japanese	SYSTEM "japanese/japanese.xml">

    <!-- NIST/OASIS test suite -->
    <!ENTITY nist-oasis		SYSTEM "oasis/oasis.xml">
	
    <!-- IBM tests -->
    <!ENTITY ibm-invalid	SYSTEM "ibm/ibm_oasis_invalid.xml">
    <!ENTITY ibm-not-wf		SYSTEM "ibm/ibm_oasis_not-wf.xml">
    <!ENTITY ibm-valid		SYSTEM "ibm/ibm_oasis_valid.xml">
    <!ENTITY ibm-xml1.1-invalid SYSTEM "ibm/xml-1.1/ibm_invalid.xml">
    <!ENTITY ibm-xml1.1-not-wf  SYSTEM "ibm/xml-1.1/ibm_not-wf.xml">
    <!ENTITY ibm-xml1.1-valid   SYSTEM "ibm/xml-1.1/ibm_valid.xml">

    <!-- Edinburgh University tests -->
    <!ENTITY eduni-errata2e	SYSTEM "eduni/errata-2e/errata2e.xml">
    <!ENTITY eduni-xml11	SYSTEM "eduni/xml-1.1/xml11.xml">
    <!ENTITY eduni-ns10		SYSTEM "eduni/namespaces/1.0/rmt-ns10.xml">
    <!ENTITY eduni-ns11		SYSTEM "eduni/namespaces/1.1/rmt-ns11.xml">
    <!ENTITY eduni-errata3e	SYSTEM "eduni/errata-3e/errata3e.xml">
    <!ENTITY eduni-nse		SYSTEM "eduni/namespaces/errata-1e/errata1e.xml">
] >
<TESTSUITE PROFILE="XML 1.0 (2nd edition) W3C Conformance Test Suite, 6 October 2000">
<TESTCASES PROFILE="James Clark  XML 1.0 Tests" xml:base="xmltest/">
    &jclark-xmltest;
</TESTCASES>

<TESTCASES PROFILE="Fuji Xerox Japanese Text Tests XML 1.0 Tests" xml:base="japanese/">    
    &xerox-japanese;
</TESTCASES>

<TESTCASES PROFILE="Sun Microsystems XML Tests" xml:base="sun/">
    &sun-valid;
    &sun-invalid;
    &sun-not-wf;
    &sun-error;
</TESTCASES>

<TESTCASES PROFILE="OASIS/NIST XML 1.0 Tests" xml:base="oasis/">
    &nist-oasis;
</TESTCASES>
    
<TESTCASES PROFILE="IBM XML 1.0 Tests" xml:base="ibm/">
    &ibm-invalid;
    &ibm-not-wf;
    &ibm-valid;
</TESTCASES>
<!-- Wrapping TESTCASES elements below added by Dieter KÃ¶hler -->
<TESTCASES PROFILE="IBM XML 1.1 Tests" xml:base="ibm/xml-1.1/">
    &ibm-xml1.1-invalid;
    &ibm-xml1.1-not-wf;
    &ibm-xml1.1-valid;
</TESTCASES>

<TESTCASES xml:base="eduni/errata-2e/">
    &eduni-errata2e;
</TESTCASES>
<TESTCASES xml:base="eduni/xml-1.1/">
    &eduni-xml11;
</TESTCASES>
<TESTCASES xml:base="eduni/namespaces/1.0/">
    &eduni-ns10;
</TESTCASES>
<TESTCASES xml:base="eduni/namespaces/1.1/">
    &eduni-ns11;
</TESTCASES>
<TESTCASES xml:base="eduni/errata-3e/">
    &eduni-errata3e;
</TESTCASES>
<TESTCASES xml:base="eduni/namespaces/errata-1e/">
    &eduni-nse;
</TESTCASES>

</TESTSUITE>
