<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mime-info [
<!ELEMENT mime-info (mime-type)+>
<!ATTLIST mime-info xmlns CDATA #FIXED "http://www.freedesktop.org/standards/shared-mime-info">
<!ELEMENT mime-type (comment+ , (acronym , expanded-acronym)? , (icon | generic-icon | glob | magic | treemagic | root-XML | alias | sub-class-of)*)>
<!ATTLIST mime-type type CDATA #REQUIRED>
<!-- a comment describing a document with the respective MIME type. Example: "WMV video" --><!ELEMENT comment (#PCDATA)>
<!ATTLIST comment xml:lang CDATA #IMPLIED>
<!-- a comment describing the respective unexpanded MIME type acronym. Example: "WMV" --><!ELEMENT acronym (#PCDATA)>
<!-- a comment describing the respective expanded MIME type acronym. Example: "Windows Media Video" --><!ELEMENT expanded-acronym (#PCDATA)>
<!ELEMENT icon EMPTY>
<!ATTLIST icon name CDATA #REQUIRED>
<!-- a generic icon name as per the Icon Naming Specification, only required if computing
  it from the mime-type would not work, See "generic-icon" in the Shared Mime Specification --><!ELEMENT generic-icon EMPTY>
<!ATTLIST generic-icon name (application-x-executable | audio-x-generic | emblem-symbolic-link | folder | font-x-generic | image-x-generic | media-floppy | media-optical | package-x-generic | text-html | text-x-generic | text-x-generic-template | text-x-script | video-x-generic | x-office-address-book | x-office-calendar | x-office-document | x-office-presentation | x-office-spreadsheet) #REQUIRED>
<!ELEMENT glob EMPTY>
<!ATTLIST glob pattern CDATA #REQUIRED>
<!ATTLIST glob weight CDATA "50">
<!ATTLIST glob case-sensitive CDATA #IMPLIED>
<!ELEMENT magic (match)+>
<!ATTLIST magic priority CDATA "50">
<!ELEMENT match (match)*>
<!ATTLIST match offset CDATA #REQUIRED>
<!ATTLIST match type (string | big16 | big32 | little16 | little32 | host16 | host32 | byte) #REQUIRED>
<!ATTLIST match value CDATA #REQUIRED>
<!ATTLIST match mask CDATA #IMPLIED>
<!ELEMENT treemagic (treematch)+>
<!ATTLIST treemagic priority CDATA "50">
<!ELEMENT treematch (treematch)*>
<!ATTLIST treematch path CDATA #REQUIRED>
<!ATTLIST treematch type (file | directory | link) #IMPLIED>
<!ATTLIST treematch match-case (true | false) #IMPLIED>
<!ATTLIST treematch executable (true | false) #IMPLIED>
<!ATTLIST treematch non-empty (true | false) #IMPLIED>
<!ATTLIST treematch mimetype CDATA #IMPLIED>
<!ELEMENT root-XML EMPTY>
<!ATTLIST root-XML namespaceURI CDATA #REQUIRED>
<!ATTLIST root-XML localName CDATA #REQUIRED>
<!ELEMENT alias EMPTY>
<!ATTLIST alias type CDATA #REQUIRED>
<!ELEMENT sub-class-of EMPTY>
<!ATTLIST sub-class-of type CDATA #REQUIRED>
]>
<!--
The freedesktop.org shared MIME database (this file) was created by merging
several existing MIME databases (all released under the GNU GPL).

It comes with ABSOLUTELY NO WARRANTY, to the extent permitted by law. You may
redistribute copies of freedesktop.org.xml under the terms of the GNU General
Public License version 2 or later. For more information about these matters,
see the file named COPYING.

The latest version is available from:

	http://www.freedesktop.org/wiki/Software/shared-mime-info/

To extend this database, users and applications should create additional
XML files in the 'packages' directory and run the update-mime-database
command to generate the output files.
-->
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/x-atari-2600-rom">
    <comment>Atari 2600 ROM</comment>
    <comment xml:lang="zh_TW">雅達利 2600 ROM</comment>
    <comment xml:lang="zh_CN">雅达利 2600 ROM</comment>
    <comment xml:lang="uk">Atari 2600 ROM</comment>
    <comment xml:lang="tr">Atari 2600 ROM</comment>
    <comment xml:lang="sv">Atari 2600-rom</comment>
    <comment xml:lang="sr">Атари 2600 РОМ</comment>
    <comment xml:lang="sq">ROM Atari 2600</comment>
    <comment xml:lang="sl">Atari 2600 ROM</comment>
    <comment xml:lang="si">Atari 2600 ROM</comment>
    <comment xml:lang="ru">Atari 2600 ROM</comment>
    <comment xml:lang="pt_BR">ROM do Atari 2600</comment>
    <comment xml:lang="pt">ROM Atari 2600</comment>
    <comment xml:lang="pl">Plik ROM konsoli Atari 2600</comment>
    <comment xml:lang="nl">Atari 2600-ROM</comment>
    <comment xml:lang="ko">아타리 2600 롬</comment>
    <comment xml:lang="kk">Atari 2600 ROM</comment>
    <comment xml:lang="ka">Atari 2600 ROM</comment>
    <comment xml:lang="ja">Atari 2600 ROM</comment>
    <comment xml:lang="it">ROM Atari 2600</comment>
    <comment xml:lang="is">Atari 2600 ROM</comment>
    <comment xml:lang="id">Atari 2600 ROM</comment>
    <comment xml:lang="hu">Atari 2600 ROM</comment>
    <comment xml:lang="hr">Atari 2600 ROM</comment>
    <comment xml:lang="he">Atari 2600 ROM</comment>
    <comment xml:lang="gl">ROM de Atari 2600</comment>
    <comment xml:lang="fur">ROM Atari 2600</comment>
    <comment xml:lang="fr">ROM Atari 2600</comment>
    <comment xml:lang="fi">Atari 2600 -ROM</comment>
    <comment xml:lang="eu">Atari 2600 ROMa</comment>
    <comment xml:lang="es">ROM de Atari 2600</comment>
    <comment xml:lang="en_GB">Atari 2600 ROM</comment>
    <comment xml:lang="de">Atari-2600-ROM</comment>
    <comment xml:lang="da">Atari 2600-ROM</comment>
    <comment xml:lang="ca">ROM d'Atari 2600</comment>
    <comment xml:lang="bg">ROM — Atari 2600</comment>
    <comment xml:lang="be">Atari 2600 ROM</comment>
    <comment xml:lang="ar">روم Atari 2600</comment>
    <generic-icon name="application-x-executable"/>
    <glob pattern="*.a26"/>
  </mime-type>
  <mime-type type="application/x-atari-7800-rom">
    <comment>Atari 7800 ROM</comment>
    <comment xml:lang="zh_TW">雅達利 7800 ROM</comment>
    <comment xml:lang="zh_CN">雅达利 7800 ROM</comment>
    <comment xml:lang="uk">Atari 7800 ROM</comment>
    <comment xml:lang="tr">Atari 7800 ROM</comment>
    <comment xml:lang="sv">Atari 7800-rom</comment>
    <comment xml:lang="sr">Атари 7800 РОМ</comment>
    <comment xml:lang="sq">ROM Atari 7800</comment>
    <comment xml:lang="sl">Atari 7800 ROM</comment>
    <comment xml:lang="si">Atari 7800 ROM</comment>
    <comment xml:lang="ru">Atari 7800 ROM</comment>
    <comment xml:lang="pt_BR">ROM do Atari 7800</comment>
    <comment xml:lang="pt">ROM Atari 7800</comment>
    <comment xml:lang="pl">Plik ROM konsoli Atari 7800</comment>
    <comment xml:lang="nl">Atari 7800-ROM</comment>
    <comment xml:lang="ko">아타리 7800 롬</comment>
    <comment xml:lang="kk">Atari 7800 ROM</comment>
    <comment xml:lang="ka">Atari 7800 ROM</comment>
    <comment xml:lang="ja">Atari 7800 ROM</comment>
    <comment xml:lang="it">ROM Atari 7800</comment>
    <comment xml:lang="is">Atari 7800 ROM</comment>
    <comment xml:lang="id">Atari 7800 ROM</comment>
    <comment xml:lang="hu">Atari 7800 ROM</comment>
    <comment xml:lang="hr">Atari 7800 ROM</comment>
    <comment xml:lang="he">Atari 7800 ROM</comment>
    <comment xml:lang="gl">ROM de Atari 7800</comment>
    <comment xml:lang="fur">ROM Atari 7800</comment>
    <comment xml:lang="fr">ROM Atari 7800</comment>
    <comment xml:lang="fi">Atari 7800 -ROM</comment>
    <comment xml:lang="eu">Atari 7800 ROMa</comment>
    <comment xml:lang="es">ROM de Atari 7800</comment>
    <comment xml:lang="en_GB">Atari 7800 ROM</comment>
    <comment xml:lang="de">Atari-7800-ROM</comment>
    <comment xml:lang="da">Atari 7800-ROM</comment>
    <comment xml:lang="ca">ROM d'Atari 7800</comment>
    <comment xml:lang="bg">ROM — Atari 7800</comment>
    <comment xml:lang="be">Atari 7800 ROM</comment>
    <comment xml:lang="ar">روم Atari 7800</comment>
    <generic-icon name="application-x-executable"/>
    <glob pattern="*.a78"/>
    <magic>
      <match type="string" value="ATARI7800" offset="1"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-atari-lynx-rom">
    <comment>Atari Lynx ROM</comment>
    <comment xml:lang="zh_TW">雅達利 Lynx ROM</comment>
    <comment xml:lang="zh_CN">雅达利 Lynx ROM</comment>
    <comment xml:lang="uk">Atari Lynx ROM</comment>
    <comment xml:lang="tr">Atari Lynx ROM</comment>
    <comment xml:lang="sv">Atari Lynx-rom</comment>
    <comment xml:lang="sr">Атари Линкс РОМ</comment>
    <comment xml:lang="sq">ROM Atari Lynx</comment>
    <comment xml:lang="sl">Atari Lynx ROM</comment>
    <comment xml:lang="si">Atari Lynx ROM</comment>
    <comment xml:lang="ru">Atari Lynx ROM</comment>
    <comment xml:lang="pt_BR">ROM do Atari Lynx</comment>
    <comment xml:lang="pt">ROM Atari Lynx</comment>
    <comment xml:lang="pl">Plik ROM konsoli Atari Lynx</comment>
    <comment xml:lang="nl">Atari Lynx-ROM</comment>
    <comment xml:lang="ko">아타리 링스 롬</comment>
    <comment xml:lang="kk">Atari Lynx ROM</comment>
    <comment xml:lang="ka">Atari Lynx ROM</comment>
    <comment xml:lang="ja">Atari Lynx ROM</comment>
    <comment xml:lang="it">ROM Atari Lynx</comment>
    <comment xml:lang="is">Atari Lynx ROM</comment>
    <comment xml:lang="id">Atari Lynx ROM</comment>
    <comment xml:lang="hu">Atari Lynx ROM</comment>
    <comment xml:lang="hr">Atari Lynx ROM</comment>
    <comment xml:lang="he">Atari Lynx ROM</comment>
    <comment xml:lang="gl">ROM de Atari Lynx</comment>
    <comment xml:lang="fur">ROM Atari Lynx</comment>
    <comment xml:lang="fr">ROM Atari Lynx</comment>
    <comment xml:lang="fi">Atari Lynx -ROM</comment>
    <comment xml:lang="eu">Atari Lynx ROMa</comment>
    <comment xml:lang="es">ROM de Atari Lynx</comment>
    <comment xml:lang="en_GB">Atari Lynx ROM</comment>
    <comment xml:lang="de">Atari-Lynx-ROM</comment>
    <comment xml:lang="da">Atari Lynx-ROM</comment>
    <comment xml:lang="ca">ROM d'Atari Lynx</comment>
    <comment xml:lang="bg">ROM — Atari Lynx</comment>
    <comment xml:lang="be">Atari Lynx ROM</comment>
    <comment xml:lang="ar">روم Atari Lynx</comment>
    <generic-icon name="application-x-executable"/>
    <glob pattern="*.lnx"/>
    <magic>
      <match type="string" value="LYNX" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/andrew-inset">
    <comment>ATK inset</comment>
    <comment xml:lang="zh_TW">ATK 內嵌</comment>
    <comment xml:lang="zh_CN">ATK 嵌入对象</comment>
    <comment xml:lang="vi">Bộ dát ATK</comment>
    <comment xml:lang="uk">вкладка ATK</comment>
    <comment xml:lang="tr">ATK iç metni</comment>
    <comment xml:lang="sv">ATK-inlägg</comment>
    <comment xml:lang="sr">АТК уметак</comment>
    <comment xml:lang="sl">Vložka ATK</comment>
    <comment xml:lang="si">ATK ඇතුළු කිරීම</comment>
    <comment xml:lang="sk">Vložka ATK</comment>
    <comment xml:lang="ru">Вкладка ATK</comment>
    <comment xml:lang="ro">Inset ATK</comment>
    <comment xml:lang="pt_BR">Conjunto de entrada do ATK</comment>
    <comment xml:lang="pt">Suplemento ATK</comment>
    <comment xml:lang="pl">Wstawka ATK</comment>
    <comment xml:lang="oc">encart ATK</comment>
    <comment xml:lang="nn">ATK-innskot</comment>
    <comment xml:lang="nl">ATK-invoegsel</comment>
    <comment xml:lang="nb">ATK-innsats</comment>
    <comment xml:lang="lv">ATK ielaidums</comment>
    <comment xml:lang="lt">ATK inset</comment>
    <comment xml:lang="ko">ATK 인세트</comment>
    <comment xml:lang="kk">ATK беті</comment>
    <comment xml:lang="ja">ATK インセット</comment>
    <comment xml:lang="it">Inset ATK</comment>
    <comment xml:lang="is">ATK innfelling</comment>
    <comment xml:lang="id">Inset ATK</comment>
    <comment xml:lang="ia">Folio intercalari ATK</comment>
    <comment xml:lang="hu">ATK betét</comment>
    <comment xml:lang="hr">ATK umetak</comment>
    <comment xml:lang="he">תוספת ATK</comment>
    <comment xml:lang="gl">conxunto ATK</comment>
    <comment xml:lang="ga">intlis ATK</comment>
    <comment xml:lang="fur">inset ATK</comment>
    <comment xml:lang="fr">encart ATK</comment>
    <comment xml:lang="fo">ATK innskot</comment>
    <comment xml:lang="fi">ATK-osio</comment>
    <comment xml:lang="eu">ATK sartzapena</comment>
    <comment xml:lang="es">inserción ATK</comment>
    <comment xml:lang="en_GB">ATK inset</comment>
    <comment xml:lang="el">Ένθετο ATK</comment>
    <comment xml:lang="de">ATK-Inset</comment>
    <comment xml:lang="da">ATK-indsættelse</comment>
    <comment xml:lang="cs">vložka ATK</comment>
    <comment xml:lang="ca">ATK inset</comment>
    <comment xml:lang="bg">Притурка — ATK</comment>
    <comment xml:lang="be@latin">Ustaŭka ATK</comment>
    <comment xml:lang="be">устаўка ATK</comment>
    <comment xml:lang="ar">شكل ATK</comment>
    <acronym>ATK</acronym>
    <expanded-acronym>Andrew Toolkit</expanded-acronym>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.ez"/>
  </mime-type>
  <mime-type type="application/epub+zip">
    <comment>Electronic book document</comment>
    <comment xml:lang="zh_TW">電子書文件</comment>
    <comment xml:lang="uk">документ електронної книги</comment>
    <comment xml:lang="sv">Elektroniskt bokdokument</comment>
    <comment xml:lang="sq">Dokument libri elektronik</comment>
    <comment xml:lang="ru">Документ электронной книги</comment>
    <comment xml:lang="pt_BR">Documento de livro eletrônico</comment>
    <comment xml:lang="pl">Dokument książki elektronicznej</comment>
    <comment xml:lang="ja">電子書籍</comment>
    <comment xml:lang="it">Documento libro elettronico</comment>
    <comment xml:lang="gl">Documento de libro electrónico</comment>
    <comment xml:lang="eu">Liburu elektronikoa</comment>
    <comment xml:lang="es">documento de libro electrónico</comment>
    <comment xml:lang="de">E-Book</comment>
    <comment xml:lang="be">электроннай кніга</comment>
    <sub-class-of type="application/zip"/>
    <generic-icon name="x-office-document"/>
    <magic priority="70">
      <match type="string" value="PK\003\004" offset="0">
        <match type="string" value="mimetype" offset="30">
          <match type="string" value="application/epub+zip" offset="38"/>
          <match type="string" value="application/epub+zip" offset="43"/>
        </match>
      </match>
    </magic>
    <glob pattern="*.epub"/>
  </mime-type>
  <mime-type type="application/vnd.amazon.mobi8-ebook">
    <comment>Kindle book document</comment>
    <comment xml:lang="zh_TW">Kindle 書文件</comment>
    <comment xml:lang="zh_CN">Kindle 电子书文档</comment>
    <comment xml:lang="uk">документ книги Kindle</comment>
    <comment xml:lang="tr">Kindle kitap belgesi</comment>
    <comment xml:lang="sv">Kindle-bokdokument</comment>
    <comment xml:lang="sr">Документ Киндл књиге</comment>
    <comment xml:lang="sq">dokument libri Kindle</comment>
    <comment xml:lang="sl">Dokument knjige Kindle</comment>
    <comment xml:lang="si">Kindle පොත් ලේඛනය</comment>
    <comment xml:lang="ru">Документ электронной книги Kindle</comment>
    <comment xml:lang="pt_BR">Documento livro do Kindle</comment>
    <comment xml:lang="pt">documento de livro eletrónico do Kindle</comment>
    <comment xml:lang="pl">Dokument książki Kindle</comment>
    <comment xml:lang="oc">document libre Kindle</comment>
    <comment xml:lang="nl">Kindle-boekdocument</comment>
    <comment xml:lang="lt">Kindle knygos dokumentas</comment>
    <comment xml:lang="ko">Kindle 책 문서</comment>
    <comment xml:lang="kk">Kindle кітап құжаты</comment>
    <comment xml:lang="ja">キンドルブックドキュメント</comment>
    <comment xml:lang="it">Documento libro Kindle</comment>
    <comment xml:lang="is">Kindle rafbókarskjal</comment>
    <comment xml:lang="id">Dokumen buku Kindle</comment>
    <comment xml:lang="hu">Kindle könyvdokumentum</comment>
    <comment xml:lang="hr">Dokument Kindle knjige</comment>
    <comment xml:lang="he">מסמך ספר Kindle</comment>
    <comment xml:lang="gl">Documento de libro de Kindle</comment>
    <comment xml:lang="fr">document livre Kindle</comment>
    <comment xml:lang="fi">Kindle book -asiakirja</comment>
    <comment xml:lang="eu">Kindle liburu-dokumentua</comment>
    <comment xml:lang="es">documento de libro de Kindle</comment>
    <comment xml:lang="en_GB">Kindle book document</comment>
    <comment xml:lang="de">Kindle E-Book</comment>
    <comment xml:lang="da">Kindle-bogdokument</comment>
    <comment xml:lang="ca">document de llibre Kindle</comment>
    <comment xml:lang="be">дакумент кнігі Kindle</comment>
    <comment xml:lang="ar">مستند كتاب كندل</comment>
    <sub-class-of type="application/x-mobipocket-ebook"/>
    <glob pattern="*.azw3"/>
    <glob pattern="*.kfx"/>
    <alias type="application/x-mobi8-ebook"/>
  </mime-type>
  <mime-type type="application/illustrator">
    <comment>Adobe Illustrator document</comment>
    <comment xml:lang="zh_TW">Adobe Illustrator 文件</comment>
    <comment xml:lang="zh_CN">Adobe Illustrator 文档</comment>
    <comment xml:lang="vi">Tài liệu Adobe Illustrator</comment>
    <comment xml:lang="uk">документ Adobe Illustrator</comment>
    <comment xml:lang="tr">Adobe Illustrator belgesi</comment>
    <comment xml:lang="sv">Adobe Illustrator-dokument</comment>
    <comment xml:lang="sr">документ Адобе илустратора</comment>
    <comment xml:lang="sq">dokument Adobe Illustrator</comment>
    <comment xml:lang="sl">Dokument Adobe Illustrator</comment>
    <comment xml:lang="si">Adobe Illustrator ලේඛනය</comment>
    <comment xml:lang="sk">Dokument Adobe Illustrator</comment>
    <comment xml:lang="ru">Документ Adobe Illustrator</comment>
    <comment xml:lang="ro">Document Adobe Illustrator</comment>
    <comment xml:lang="pt_BR">Documento do Adobe Illustrator</comment>
    <comment xml:lang="pt">documento Adobe Illustrator</comment>
    <comment xml:lang="pl">Dokument Adobe Illustrator</comment>
    <comment xml:lang="oc">document Adobe Illustrator</comment>
    <comment xml:lang="nn">Adobe Illustrator-dokument</comment>
    <comment xml:lang="nl">Adobe Illustrator-document</comment>
    <comment xml:lang="nb">Adobe Illustrator-dokument</comment>
    <comment xml:lang="ms">Dokumen Adobe Illustrator</comment>
    <comment xml:lang="lv">Adobe Illustrator dokuments</comment>
    <comment xml:lang="lt">Adobe Illustrator dokumentas</comment>
    <comment xml:lang="ko">Adobe Illustrator 문서</comment>
    <comment xml:lang="kk">Adobe Illustrator құжаты</comment>
    <comment xml:lang="ka">Adobe Illustrator-ის დოკუმენტი</comment>
    <comment xml:lang="ja">Adobe Illustrator ドキュメント</comment>
    <comment xml:lang="it">Documento Adobe Illustrator</comment>
    <comment xml:lang="is">Adobe Illustrator skjal</comment>
    <comment xml:lang="id">Dokumen Adobe Illustrator</comment>
    <comment xml:lang="ia">Documento Adobe Illustrator</comment>
    <comment xml:lang="hu">Adobe Illustrator-dokumentum</comment>
    <comment xml:lang="hr">Adobe Illustrator dokument</comment>
    <comment xml:lang="he">מסמך Adobe Ill</comment>
    <comment xml:lang="gl">documento de Adobe Ilustrator</comment>
    <comment xml:lang="ga">cáipéis Adobe Illustrator</comment>
    <comment xml:lang="fur">document Adobe Illustrator</comment>
    <comment xml:lang="fr">document Adobe Illustrator</comment>
    <comment xml:lang="fo">Adobe Illustrator skjal</comment>
    <comment xml:lang="fi">Adobe Illustrator -asiakirja</comment>
    <comment xml:lang="eu">Adobe Illustrator dokumentua</comment>
    <comment xml:lang="es">documento de Adobe Illustrator</comment>
    <comment xml:lang="eo">dokumento de Adobe Illustrator</comment>
    <comment xml:lang="en_GB">Adobe Illustrator document</comment>
    <comment xml:lang="el">Έγγραφο Adobe Illustrator</comment>
    <comment xml:lang="de">Adobe-Illustrator-Dokument</comment>
    <comment xml:lang="da">Adobe Illustrator-dokument</comment>
    <comment xml:lang="cs">dokument Adobe Illustrator</comment>
    <comment xml:lang="ca">document d'Adobe Illustrator</comment>
    <comment xml:lang="bg">Документ — Adobe Illustrator</comment>
    <comment xml:lang="be@latin">Dakument Adobe Illustrator</comment>
    <comment xml:lang="be">дакумент Adobe Illustrator</comment>
    <comment xml:lang="ast">Documentu d'Adobe Illustrator</comment>
    <comment xml:lang="ar">مستند أدوبي إليستريتور</comment>
    <comment xml:lang="af">Adobe Illustrator-dokument</comment>
    <generic-icon name="image-x-generic"/>
    <glob pattern="*.ai"/>
    <alias type="application/vnd.adobe.illustrator"/>
  </mime-type>
  <mime-type type="application/mac-binhex40">
    <comment>Macintosh BinHex-encoded file</comment>
    <comment xml:lang="zh_TW">Macintosh BinHex 編碼檔</comment>
    <comment xml:lang="zh_CN">Macintosh BinHex 编码的文件</comment>
    <comment xml:lang="vi">Tập tin đã mã hoá BinHex của Macintosh</comment>
    <comment xml:lang="uk">файл закодований Macintosh BinHex</comment>
    <comment xml:lang="tr">Macintosh BinHex-şifreli dosya</comment>
    <comment xml:lang="sv">Macintosh BinHex-kodad fil</comment>
    <comment xml:lang="sr">Мекинтошова БинХекс-кодирана датотека</comment>
    <comment xml:lang="sq">kartelë Macintosh koduar me BinHex</comment>
    <comment xml:lang="sl">Kodirana datoteka Macintosh (BinHex)</comment>
    <comment xml:lang="si">Macintosh BinHex-කේතනය කළ ගොනුව</comment>
    <comment xml:lang="sk">Súbor kódovaný pomocou Macintosh BinHex</comment>
    <comment xml:lang="ru">Файл Macintosh закодированный BinHex</comment>
    <comment xml:lang="ro">Fișier codat Macintosh BinHex</comment>
    <comment xml:lang="pt_BR">Arquivo do Macintosh codificado com BinHex</comment>
    <comment xml:lang="pt">ficheiro codificado em BinHex de Macintosh</comment>
    <comment xml:lang="pl">Zakodowany w BinHex plik Macintosh</comment>
    <comment xml:lang="oc">fichièr encodat Macintosh BinHex</comment>
    <comment xml:lang="nn">Macintosh BinHex-koda fil</comment>
    <comment xml:lang="nl">Macintosh BinHex-gecodeerd bestand</comment>
    <comment xml:lang="nb">Macintosh BinHe-kodet arkiv</comment>
    <comment xml:lang="ms">Fail terenkod-BinHex Macintosh</comment>
    <comment xml:lang="lv">Macintosh BinHex-kodēts datne</comment>
    <comment xml:lang="lt">Macintosh BinHex-encoded failas</comment>
    <comment xml:lang="ko">매킨토시 BinHex 인코딩된 압축 파일</comment>
    <comment xml:lang="kk">Macintosh BinHex кодталған файлы</comment>
    <comment xml:lang="ja">Macintosh BinHex エンコードファイル</comment>
    <comment xml:lang="it">File Macintosh codificato BinHex</comment>
    <comment xml:lang="is">Macintosh BinHex-kóðuð skrá</comment>
    <comment xml:lang="id">Berkas tersandi Macintosh BinHex</comment>
    <comment xml:lang="ia">File codificate in BinHex de Macintosh</comment>
    <comment xml:lang="hu">Macintosh BinHex kódolású fájl</comment>
    <comment xml:lang="hr">Macintosh BinHex-kôdirana datoteka</comment>
    <comment xml:lang="he">קובץ בקידוד Macintosh BinHex</comment>
    <comment xml:lang="gl">ficheiro de Macintosh codificado con BinHex</comment>
    <comment xml:lang="ga">comhad ionchódaithe le Macintosh BinHex</comment>
    <comment xml:lang="fur">file di Macintosh codificât BinHex</comment>
    <comment xml:lang="fr">fichier codé Macintosh BinHex</comment>
    <comment xml:lang="fo">Macintosh BinHex-bronglað fíla</comment>
    <comment xml:lang="fi">Macintosh BinHex -koodattu tiedosto</comment>
    <comment xml:lang="eu">Macintosh BinHex-ekin kodetutako fitxategia</comment>
    <comment xml:lang="es">archivo Macintosh codificado con BinHex</comment>
    <comment xml:lang="eo">dosiero kodigita laŭ Macintosh BinHex</comment>
    <comment xml:lang="en_GB">Macintosh BinHex-encoded file</comment>
    <comment xml:lang="el">Αρχείο Macintosh κωδικοποίησης BinHex</comment>
    <comment xml:lang="de">Macintosh-Datei (BinHex-verschlüsselt)</comment>
    <comment xml:lang="da">Macintosh BinHex-kodet fil</comment>
    <comment xml:lang="cy">Ffeil BinHex-amgodwyd Macintosh</comment>
    <comment xml:lang="cs">soubor kódovaný pomocí Macintosh BinHex</comment>
    <comment xml:lang="ca">fitxer amb codificació BinHex de Macintosh</comment>
    <comment xml:lang="bg">Файл — кодиран във формат BinHex за Macintosh</comment>
    <comment xml:lang="be@latin">Fajł Macintosh, BinHex-zakadavany</comment>
    <comment xml:lang="be">файл з кадаваннем Macintosh BinHex</comment>
    <comment xml:lang="az">Macintosh BinHex-kodlanmış fayl</comment>
    <comment xml:lang="ast">Ficheru codificáu en BinHex de Machintosh</comment>
    <comment xml:lang="ar">ملف Macintosh BinHex مشفر</comment>
    <comment xml:lang="af">Macintosh BinHex-geënkodeerde lêer</comment>
    <sub-class-of type="text/plain"/>
    <generic-icon name="package-x-generic"/>
    <magic>
      <match type="string" value="(This file must be converted with BinHex 4.0)" offset="0"/>
      <match type="string" value="(This file must be converted; you knew that already.)" offset="0"/>
    </magic>
    <glob pattern="*.hqx"/>
  </mime-type>
  <mime-type type="application/mathematica">
    <comment>Mathematica Notebook file</comment>
    <comment xml:lang="zh_TW">Mathematica 筆記本檔案</comment>
    <comment xml:lang="zh_CN">Mathematica 笔记本文件</comment>
    <comment xml:lang="uk">файл нотатника Mathematica</comment>
    <comment xml:lang="tr">Mathematica Notebook dosyası</comment>
    <comment xml:lang="sv">Mathematica-anteckningsboksfil</comment>
    <comment xml:lang="sq">kartelë Mathematica Notebook</comment>
    <comment xml:lang="sl">Datoteka Mathematica Notebook</comment>
    <comment xml:lang="si">Mathematica Notebook ගොනුව</comment>
    <comment xml:lang="ru">Файл Mathematica Notebook</comment>
    <comment xml:lang="pt_BR">Arquivo Notebook do Mathematica</comment>
    <comment xml:lang="pt">ficheiro de Mathematica Notebook do Wolfram</comment>
    <comment xml:lang="pl">Plik notatnika Mathematica</comment>
    <comment xml:lang="nl">Mathematica Notebook-bestand</comment>
    <comment xml:lang="ko">Mathematica 기록장 파일</comment>
    <comment xml:lang="kk">Mathematica блокнот файлы</comment>
    <comment xml:lang="ka">Mathematica Notebook-ის ფაილი</comment>
    <comment xml:lang="ja">Mathematica ノートブックファイル</comment>
    <comment xml:lang="it">File Mathematica Notebook</comment>
    <comment xml:lang="is">Mathematica Notebook skrá</comment>
    <comment xml:lang="id">Berkas Mathematica Notebook</comment>
    <comment xml:lang="hu">Mathematica munkafüzetfájl</comment>
    <comment xml:lang="hr">Mathematica Notebook datoteka</comment>
    <comment xml:lang="he">קובץ מחברת של Mathematica</comment>
    <comment xml:lang="gl">Ficheiro de caderno de Mathematica</comment>
    <comment xml:lang="fr">fichier carnet Mathematica</comment>
    <comment xml:lang="fi">Mathematica Notebook -tiedosto</comment>
    <comment xml:lang="eu">Mathematica Notebook fitxategia</comment>
    <comment xml:lang="es">archivo de Mathematica Notebook</comment>
    <comment xml:lang="en_GB">Mathematica Notebook file</comment>
    <comment xml:lang="de">Mathematica-Notebook-Datei</comment>
    <comment xml:lang="da">Mathematica Notebook-fil</comment>
    <comment xml:lang="ca">llibreta de Mathematica Notebook</comment>
    <comment xml:lang="bg">Скицник — Mathematica</comment>
    <comment xml:lang="be">файл Mathematica Notebook</comment>
    <comment xml:lang="ar">ملف دفتر ماثماتيكا</comment>
    <sub-class-of type="text/plain"/>
    <generic-icon name="x-office-document"/>
    <glob pattern="*.nb"/>
    <magic>
      <match value="(************** Content-type: application/mathematica" type="string" offset="0"/>
      <match value="This notebook can be used on any computer system with Mathematica" type="string" offset="100:256"/>
      <match value="This is a Mathematica Notebook file.  It contains ASCII text" type="string" offset="10:256"/>
    </magic>
    <alias type="application/x-mathematica"/>
  </mime-type>
  <mime-type type="application/mathml+xml">
    <comment>MathML document</comment>
    <comment xml:lang="zh_TW">MathML 文件</comment>
    <comment xml:lang="zh_CN">MathML 文档</comment>
    <comment xml:lang="vi">Tài liệu MathML</comment>
    <comment xml:lang="uk">документ MathML</comment>
    <comment xml:lang="tr">MathML belgesi</comment>
    <comment xml:lang="sv">MathML-dokument</comment>
    <comment xml:lang="sr">МатМЛ документ</comment>
    <comment xml:lang="sq">dokument MathML</comment>
    <comment xml:lang="sl">Dokument MathML</comment>
    <comment xml:lang="si">MathML ලේඛනය</comment>
    <comment xml:lang="sk">Dokument MathML</comment>
    <comment xml:lang="ru">Документ MathML</comment>
    <comment xml:lang="ro">Document MathML</comment>
    <comment xml:lang="pt_BR">Documento do MathML</comment>
    <comment xml:lang="pt">documento MathML</comment>
    <comment xml:lang="pl">Dokument MathML</comment>
    <comment xml:lang="oc">document MathML</comment>
    <comment xml:lang="nn">MathML-dokument</comment>
    <comment xml:lang="nl">MathML-document</comment>
    <comment xml:lang="nb">MathML-dokument</comment>
    <comment xml:lang="ms">Dokumen MathML</comment>
    <comment xml:lang="lv">MathML dokuments</comment>
    <comment xml:lang="lt">MathML dokumentas</comment>
    <comment xml:lang="ko">MathML 문서</comment>
    <comment xml:lang="kk">MathML құжаты</comment>
    <comment xml:lang="ka">MathML-ის დოკუმენტი</comment>
    <comment xml:lang="ja">MathML ドキュメント</comment>
    <comment xml:lang="it">Documento MathML</comment>
    <comment xml:lang="is">MathML skjal</comment>
    <comment xml:lang="id">Dokumen MathML</comment>
    <comment xml:lang="ia">Documento MathML</comment>
    <comment xml:lang="hu">MathML-dokumentum</comment>
    <comment xml:lang="hr">MathML dokument</comment>
    <comment xml:lang="he">מסמך MathML</comment>
    <comment xml:lang="gl">documento de MathML</comment>
    <comment xml:lang="ga">cáipéis MathML</comment>
    <comment xml:lang="fur">document MathML</comment>
    <comment xml:lang="fr">document MathML</comment>
    <comment xml:lang="fo">MathML skjal</comment>
    <comment xml:lang="fi">MathML-asiakirja</comment>
    <comment xml:lang="eu">MathML dokumentua</comment>
    <comment xml:lang="es">documento MathML</comment>
    <comment xml:lang="eo">MathML-dokumento</comment>
    <comment xml:lang="en_GB">MathML document</comment>
    <comment xml:lang="el">Έγγραφο MathML</comment>